### ISSUE TITLE
Questions about User and Authority class

### ISSUE THREAD

**Issue by zhengye1** [bfwg/angular-spring-starter#8]
I want to know why we need following field in user and authority table
created_at, updated_at, and deleted_at

Since I didn't see any data that come into those fields...

**Comment by bfwg** [comment]
Hey @zhengye1 , very good question. This is for database tables which has those fields, but we don't have this kind of table in `import.sql`. I guess those model class are outside of the scope of this repository.

Should we remove them? Since they are not directly related to the purpose of this project.
